name: simple_release

on:
  workflow_dispatch:
  push:
    branches:
      - 'simple_release/release**'
      - 'simple_release/rls**'
      - 'simple_release/cleanup**'
      - 'simple_release/clean**'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  simple_cdk1:
    uses: ./.github/workflows/simple_cdk1.yml
    secrets: inherit
  simple_cdk2:
    uses: ./.github/workflows/simple_cdk2.yml
    needs: [simple_cdk1]
    secrets: inherit
